name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu:22.04@sha256:19478ce7fc2ffbce89df29fea5725a8d12e57de52eb9ea570890dc5852aac1ac
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libgdal-dev gdal-bin libfftw3-dev
      - uses: actions/checkout@v2
        with:
            submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip
          python setup.py sdist
      - name: Test sdist install
        run: pip install dist/*.tar.gz
