name: s2p

on: [push]

jobs:

  python-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libgdal-dev gdal-bin libfftw3-dev
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Build sdist
        run: python setup.py sdist
      - name: Test sdist install
        run: pip install dist/*.tar.gz

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Build docker image
        run: docker build .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libgdal-dev gdal-bin libfftw3-dev
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Install s2p
        run: pip install -e ".[test]" --upgrade --upgrade-strategy eager
      - name: Run tests
        run: pytest tests
